### ISSUE TITLE
get_LD() error: invalid 'path' argument

### ISSUE THREAD

**Issue by jacqueline-alector** [RajLabMSSM/echoLD#11]
I am trying to compute LD matrix from summary statistics, and I want to use the 1000 genome phase 3 reference panel. 

```
echoLD::get_LD(
  query_dat = sumstats,
  locus_dir = save_dir,
  query_genome="hg38",
  LD_reference = "1KGphase3",
  superpopulation = "EUR",
  nThread = 16
)
```
This works for some loci, but not always. For example, I have a loci on chr2:8906676-9922165, the error said  `invalid 'path' argument`, but I am sure the path is correct. 

What is the issue behind it? How should I resolve this problem?

**Comment by jacqueline-alector** [comment]
I resolved this issue by converting my loci to hg19 first, before running the get_LD() function. I think the problem is that some position cannot be converted to hg38 from the reference panel which is causing this error.

**Comment by bschilder** [comment]
Thank you for reporting this @jacqueline-alector  and apologies for the delay. I'm going to take a closer look at the liftover functions and see how I can improve them to avoid these sorts of situations. I'll also add some more informative error messages when this does occur.
