### ISSUE TITLE
Locus specific LD VCF file generated from 1000genomes Reference Panel is empty

### ISSUE THREAD

**Issue by AMCalejandro** [RajLabMSSM/echoLD#3]
Hi,

It turnes out that when running the "full pipeline vignette" the bgzipped VCF file generated under ./RESULTS/GWAS/Nalls23andMe_2019/BST1/LD is empty.

I believe this is causing the "Segmentation fault (core dumped)" error, so that no finemapping tool works downstream since we are missing the locus specific LD structure.

<pre><font color="#3465A4">r$&gt;</font> <font color="#5FAF00"><b>library</b></font><font color="#D0D0D0">(echolocatoR)</font>                                                                                                                                                                                   
<font color="#CC0000">Registered S3 method overwritten by &apos;GGally&apos;:</font>
<font color="#CC0000">  method from   </font>
<font color="#CC0000">  +.gg   ggplot2</font>
<font color="#CC0000">Bioconductor version 3.12 (BiocManager 1.30.12), ?BiocManager::install for help</font>
<font color="#CC0000">Bioconductor version &apos;3.12&apos; is out-of-date; the current release version &apos;3.14&apos; is available with R version &apos;4.1&apos;; see https://bioconductor.org/install</font>
</pre>

<pre><font color="#5FAF00">data</font><font color="#D0D0D0">(</font><font color="#FFAF00">&quot;Nalls_top_SNPs&quot;</font><font color="#D0D0D0">);</font> 
    <font color="#D0D0D0">top_SNPs </font><font color="#626262">&lt;-</font><font color="#D0D0D0"> </font><font color="#5FAF00">import_topSNPs</font><font color="#D0D0D0">(</font> 
    <font color="#D0D0D0">  </font><font color="#949494"><i># topSS = &quot;~/Desktop/Fine_Mapping/Data/GWAS/Nalls23andMe_2019/Nalls2019_TableS2.xlsx&quot;,</i></font> 
    <font color="#D0D0D0">  topSS </font><font color="#626262">=</font><font color="#D0D0D0"> Nalls_top_SNPs,</font> 
    <font color="#D0D0D0">  chrom_col </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;CHR&quot;</font><font color="#D0D0D0">, </font> 
    <font color="#D0D0D0">  position_col </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;BP&quot;</font><font color="#D0D0D0">, </font> 
    <font color="#D0D0D0">  snp_col</font><font color="#626262">=</font><font color="#FFAF00">&quot;SNP&quot;</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">  pval_col</font><font color="#626262">=</font><font color="#FFAF00">&quot;P, all studies&quot;</font><font color="#D0D0D0">, </font> 
    <font color="#D0D0D0">  effect_col</font><font color="#626262">=</font><font color="#FFAF00">&quot;Beta, all studies&quot;</font><font color="#D0D0D0">, </font> 
    <font color="#D0D0D0">  gene_col</font><font color="#626262">=</font><font color="#FFAF00">&quot;Nearest Gene&quot;</font><font color="#D0D0D0">, </font> 
    <font color="#D0D0D0">  locus_col </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;Nearest Gene&quot;</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">  grouping_vars </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#AF005F">c</font><font color="#D0D0D0">(</font><font color="#FFAF00">&quot;Locus&quot;</font><font color="#D0D0D0">),</font> 
    <font color="#D0D0D0">  remove_variants </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;rs34637584&quot;</font><font color="#D0D0D0">) </font> 
    <font color="#949494"><i>#&gt; [1] &quot;+ Assigning gene_col and locus_col independently&quot;</i></font> 
    <font color="#5FAF00">head</font><font color="#D0D0D0">(top_SNPs)</font> 
</pre>

<pre>     Locus    Gene CHR       POS        SNP        P  Effect
1:   ASXL3   ASXL3  18  31304318  rs1941685 1.69e-08  0.0531
2:    BAG3    BAG3  10 121415685 rs72840788 1.57e-11  0.0763
3:    BIN3    BIN3   8  22525980  rs2280104 1.16e-08  0.0556
4:   BRIP1   BRIP1  17  59917366 rs61169879 9.28e-10  0.0820
5:    BST1    BST1   4  15737348  rs4698412 2.06e-28  0.1035
6: C5orf24 C5orf24   5 134199105 rs11950533 7.16e-09 -0.0916
</pre>

<pre><font color="#3465A4">r$&gt;</font> <font color="#D0D0D0">fullSS_path </font><font color="#626262">&lt;-</font><font color="#D0D0D0"> </font><font color="#5FAF00">example_fullSS</font><font color="#D0D0D0">(fullSS_path</font><font color="#626262">=</font><font color="#5FAF00">file.path</font><font color="#D0D0D0">(</font><font color="#FFAF00">&quot;/mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR&quot;</font><font color="#D0D0D0">,</font><font color="#FFAF00">&quot;Nalls23andMe_2019.fullSS_subset.tsv&quot;</font><font color="#D0D0D0">))</font></pre>

<pre><font color="#3465A4">r$&gt;</font> <font color="#D0D0D0">fullSS_path</font>                                                                                                                                                                                            
[1] &quot;/mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/Nalls23andMe_2019.fullSS_subset.tsv&quot;
</pre>

<pre>    <font color="#D0D0D0">                                          top_SNPs </font><font color="#626262">=</font><font color="#D0D0D0"> top_SNPs,  </font> 
    <font color="#D0D0D0">                                          </font><font color="#949494"><i>#  It&apos;s best to give absolute paths</i></font> 
    <font color="#D0D0D0">                                          results_dir </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#5FAF00">file.path</font><font color="#D0D0D0">(</font><font color="#FFAF00">&quot;/mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR&quot;</font><font color="#D0D0D0">,</font><font color="#FFAF00">&quot;results&quot;</font><font color="#D0D0D0">),</font> 
    <font color="#D0D0D0">                                          loci </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#AF005F">c</font><font color="#D0D0D0">(</font><font color="#FFAF00">&quot;BST1&quot;</font><font color="#D0D0D0">,</font><font color="#FFAF00">&quot;MEX3C&quot;</font><font color="#D0D0D0">),</font><font color="#949494"><i># top_SNPs$Locus,</i></font> 
    <font color="#D0D0D0">                                          dataset_name </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;Nalls23andMe_2019&quot;</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                                          dataset_type </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;GWAS&quot;</font><font color="#D0D0D0">,  </font> 
    <font color="#D0D0D0">                                          force_new_subset </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#0087AF">T</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                                          force_new_LD </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#0087AF">T</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                                          force_new_finemap </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#0087AF">T</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                                          remove_tmps </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#0087AF">F</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                                          </font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i># SUMMARY STATS ARGUMENTS</i></font> 
    <font color="#D0D0D0">                 fullSS_path </font><font color="#626262">=</font><font color="#D0D0D0"> fullSS_path,</font> 
    <font color="#D0D0D0">                 query_by </font><font color="#626262">=</font><font color="#FFAF00">&quot;tabix&quot;</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                 chrom_col </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;CHR&quot;</font><font color="#D0D0D0">, position_col </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;POS&quot;</font><font color="#D0D0D0">, snp_col </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;RSID&quot;</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                 pval_col </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;p&quot;</font><font color="#D0D0D0">, effect_col </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;beta&quot;</font><font color="#D0D0D0">, stderr_col </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;se&quot;</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                 freq_col </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;freq&quot;</font><font color="#D0D0D0">, MAF_col </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;calculate&quot;</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                 A1_col </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;A1&quot;</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                 A2_col </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;A2&quot;</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                 </font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i># FILTERING ARGUMENTS</i></font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i>## It&apos;s often desirable to use a larger window size </i></font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i>## (e.g. 2Mb which is bp_distance=500000*2), </i></font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i>## but we use a small window here to speed up the process. </i></font> 
    <font color="#D0D0D0">                 bp_distance </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#5F87AF">10000</font><font color="#D0D0D0">,</font><font color="#949494"><i>#500000*2,</i></font> 
    <font color="#D0D0D0">                 min_MAF </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#5F87AF">0.001</font><font color="#D0D0D0">,  </font> 
    <font color="#D0D0D0">                 trim_gene_limits </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#0087AF">F</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                 </font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i># FINE-MAPPING ARGUMENTS</i></font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i>## General</i></font> 
    <font color="#D0D0D0">                 finemap_methods </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#AF005F">c</font><font color="#D0D0D0">(</font><font color="#FFAF00">&quot;ABF&quot;</font><font color="#D0D0D0">,</font><font color="#FFAF00">&quot;FINEMAP&quot;</font><font color="#D0D0D0">,</font><font color="#FFAF00">&quot;SUSIE&quot;</font><font color="#D0D0D0">,</font><font color="#FFAF00">&quot;POLYFUN_SUSIE&quot;</font><font color="#D0D0D0">), </font> 
    <font color="#D0D0D0">                 n_causal </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#5F87AF">5</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                 PP_threshold </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#5F87AF">.95</font><font color="#D0D0D0">, </font> 
    <font color="#D0D0D0">                 </font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i># LD ARGUMENTS </i></font> 
    <font color="#D0D0D0">                 LD_reference </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;1KGphase1&quot;</font><font color="#D0D0D0">,</font><font color="#949494"><i>#&quot;UKB&quot;,</i></font> 
    <font color="#D0D0D0">                 superpopulation </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;EUR&quot;</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                 download_method </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#FFAF00">&quot;axel&quot;</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                 </font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i># PLOT ARGUMENTS </i></font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i>## general   </i></font> 
    <font color="#D0D0D0">                 plot.types</font><font color="#626262">=</font><font color="#AF005F">c</font><font color="#D0D0D0">(</font><font color="#FFAF00">&quot;fancy&quot;</font><font color="#D0D0D0">),</font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i>## Generate multiple plots of different window sizes; </i></font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i>### all SNPs, 4x zoomed-in, and a 50000bp window</i></font> 
    <font color="#D0D0D0">                 plot.zoom </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#AF005F">c</font><font color="#D0D0D0">(</font><font color="#FFAF00">&quot;all&quot;</font><font color="#D0D0D0">,</font><font color="#FFAF00">&quot;4x&quot;</font><font color="#D0D0D0">,</font><font color="#FFAF00">&quot;10x&quot;</font><font color="#D0D0D0">),</font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i>## XGR</i></font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i># plot.XGR_libnames=c(&quot;ENCODE_TFBS_ClusteredV3_CellTypes&quot;), </i></font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i>## Roadmap</i></font> 
    <font color="#D0D0D0">                 plot.Roadmap </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#0087AF">F</font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                 plot.Roadmap_query </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#5FAF00"><b>NULL</b></font><font color="#D0D0D0">,</font> 
    <font color="#D0D0D0">                 </font><font color="#949494"><i># Nott et al. (2019)</i></font> 
    <font color="#D0D0D0">                 plot.Nott_epigenome </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#0087AF">T</font><font color="#D0D0D0">, </font> 
    <font color="#D0D0D0">                 plot.Nott_show_placseq </font><font color="#626262">=</font><font color="#D0D0D0"> </font><font color="#0087AF">T</font><font color="#D0D0D0">, </font>                                                                                                                                                          
[1] &quot;+ CONDA:: Activating conda env &apos;echoR&apos;&quot;
[1] &quot;Checking for tabix installation...&quot;
[1] &quot;Checking for bcftools installation...&quot;

<font color="#CC0000">)   )  ) ))))))}}}}}}}} {{{{{{{{{(((((( (  (   (</font>
<font color="#CC0000">BST1 (1 / 2)</font>
<font color="#CC0000">)   )  ) ))))))}}}}}}}} {{{{{{{{{(((((( (  (   (</font>
[1] &quot;+ CONDA:: Identified bgzip executable in echoR env.&quot;
[1] &quot;Determining chrom type from file header&quot;
[1] &quot;LD:: Standardizing summary statistics subset.&quot;
[1] &quot;++ Preparing Gene col&quot;
[1] &quot;++ Preparing A1,A1 cols&quot;
[1] &quot;++ Preparing MAF,Freq cols&quot;
[1] &quot;++ Inferring MAF from frequency column...&quot;
[1] &quot;++ Preparing N_cases,N_controls cols&quot;
[1] &quot;++ Preparing `proportion_cases` col&quot;
[1] &quot;++ Calculating `proportion_cases`.&quot;
[1] &quot;++ Preparing N col&quot;
[1] &quot;+ Preparing sample_size (N) column&quot;
[1] &quot;++ Computing effective sample size.&quot;
[1] &quot;++ Preparing t-stat col&quot;
[1] &quot;+ Calculating t-statistic from Effect and StdErr...&quot;
[1] &quot;++ Assigning lead SNP&quot;
[1] &quot;++ Ensuring Effect, StdErr, P are numeric&quot;
[1] &quot;++ Ensuring 1 SNP per row&quot;
[1] &quot;++ Removing extra whitespace&quot;
[1] &quot;++ Saving subset ==&gt; /mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/BST1/BST1_Nalls23andMe_2019_subset.tsv.gz&quot;
[1] &quot;LD:: Using 1000Genomes as LD reference panel.&quot;
[1] &quot;LD Reference Panel = 1KGphase1&quot;
[1] &quot;+ LD:: Querying 1KG remote server.&quot;
[1] &quot;+ CONDA:: Identified tabix executable in echoR env.&quot;
[1] &quot;LD:: Querying VCF subset&quot;
[1] &quot;/home/acarrasco/.conda/envs/echoR/bin/tabix -fh -p vcf ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/release/20110521//ALL.chr4.phase1_release_v3.20101123.snps_indels_svs.genotypes.vcf.gz 4:15727389-15747197 &gt; /mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/BST1/LD/BST1.1KGphase1.vcf&quot;
Segmentation fault (core dumped)
[1] &quot;LD:BCFTOOLS:: Compressing vcf file...&quot;
[1] &quot;LD:TABIX:: Re-indexing vcf.gz...&quot;
[1] &quot;LD:BCFTOOLS:: Subsetting vcf to only include EUR individuals ( 378 / 1091 ).&quot;
Failed to read from /mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/BST1/LD/BST1.1KGphase1.vcf.gz: unknown file type
[1] &quot;LD:PLINK:: Converting vcf.gz to .bed/.bim/.fam&quot;
PLINK v1.90b6.9 64-bit (4 Mar 2019)            www.cog-genomics.org/plink/1.9/
(C) 2005-2019 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to /mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/BST1/LD/plink.log.
Options in effect:
  --out /mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/BST1/LD/plink
  --vcf /mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/BST1/LD/BST1.1KGphase1.vcf.gz

257891 MB RAM detected; reserving 128945 MB for main workspace.

Error: File read failure.
[1] &quot;LD:snpStats:: Computing LD (stats = R)&quot;
<font color="#CC0000">Error in data.table::fread(bim_path, col.names = c(&quot;CHR&quot;, &quot;SNP&quot;, &quot;V3&quot;,  : </font>
<font color="#CC0000">  File &apos;/mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/BST1/LD/plink.bim&apos; does not exist or is non-readable. getwd()==&apos;/mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR&apos;</font>
<font color="#CC0000">Fine-mapping complete in:</font>
Time difference of 11.7 secs

<font color="#CC0000">)   )  ) ))))))}}}}}}}} {{{{{{{{{(((((( (  (   (</font>
<font color="#CC0000">MEX3C (2 / 2)</font>
<font color="#CC0000">)   )  ) ))))))}}}}}}}} {{{{{{{{{(((((( (  (   (</font>
[1] &quot;Determining chrom type from file header&quot;
[1] &quot;LD:: Standardizing summary statistics subset.&quot;
[1] &quot;++ Preparing Gene col&quot;
[1] &quot;++ Preparing A1,A1 cols&quot;
[1] &quot;++ Preparing MAF,Freq cols&quot;
[1] &quot;++ Inferring MAF from frequency column...&quot;
[1] &quot;++ Preparing N_cases,N_controls cols&quot;
[1] &quot;++ Preparing `proportion_cases` col&quot;
[1] &quot;++ Calculating `proportion_cases`.&quot;
[1] &quot;++ Preparing N col&quot;
[1] &quot;+ Preparing sample_size (N) column&quot;
[1] &quot;++ Computing effective sample size.&quot;
[1] &quot;++ Preparing t-stat col&quot;
[1] &quot;+ Calculating t-statistic from Effect and StdErr...&quot;
[1] &quot;++ Assigning lead SNP&quot;
[1] &quot;++ Ensuring Effect, StdErr, P are numeric&quot;
[1] &quot;++ Ensuring 1 SNP per row&quot;
[1] &quot;++ Removing extra whitespace&quot;
[1] &quot;++ Saving subset ==&gt; /mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/MEX3C/MEX3C_Nalls23andMe_2019_subset.tsv.gz&quot;
[1] &quot;LD:: Using 1000Genomes as LD reference panel.&quot;
[1] &quot;LD Reference Panel = 1KGphase1&quot;
[1] &quot;+ LD:: Querying 1KG remote server.&quot;
[1] &quot;+ CONDA:: Identified tabix executable in echoR env.&quot;
[1] &quot;LD:: Querying VCF subset&quot;
[1] &quot;/home/acarrasco/.conda/envs/echoR/bin/tabix -fh -p vcf ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/release/20110521//ALL.chr18.phase1_release_v3.20101123.snps_indels_svs.genotypes.vcf.gz 18:48673708-48692728 &gt; /mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/MEX3C/LD/MEX3C.1KGphase1.vcf&quot;
Segmentation fault (core dumped)
[1] &quot;LD:BCFTOOLS:: Compressing vcf file...&quot;
[1] &quot;LD:TABIX:: Re-indexing vcf.gz...&quot;
[1] &quot;LD:BCFTOOLS:: Subsetting vcf to only include EUR individuals ( 378 / 1091 ).&quot;
Failed to read from /mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/MEX3C/LD/MEX3C.1KGphase1.vcf.gz: unknown file type
[1] &quot;LD:PLINK:: Converting vcf.gz to .bed/.bim/.fam&quot;
PLINK v1.90b6.9 64-bit (4 Mar 2019)            www.cog-genomics.org/plink/1.9/
(C) 2005-2019 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to /mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/MEX3C/LD/plink.log.
Options in effect:
  --out /mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/MEX3C/LD/plink
  --vcf /mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/MEX3C/LD/MEX3C.1KGphase1.vcf.gz

257891 MB RAM detected; reserving 128945 MB for main workspace.

Error: File read failure.
[1] &quot;LD:snpStats:: Computing LD (stats = R)&quot;
<font color="#CC0000">Error in data.table::fread(bim_path, col.names = c(&quot;CHR&quot;, &quot;SNP&quot;, &quot;V3&quot;,  : </font>
<font color="#CC0000">  File &apos;/mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/MEX3C/LD/plink.bim&apos; does not exist or is non-readable. getwd()==&apos;/mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR&apos;</font>
<font color="#CC0000">Fine-mapping complete in:</font>
Time difference of 8.7 secs
<font color="#CC0000">Error in `[.data.table`(x, r, vars, with = FALSE) : </font>
<font color="#CC0000">  column(s) not found: SNP</font>
</pre>

**Then, we see how the loci specific LD file is empty, leading to the segmentation fault error**

<pre><font color="#4E9A06"><b>acarrasco@kronos</b></font>:<font color="#3465A4"><b>/mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/BST1/LD</b></font>$ gunzip BST1.1KGphase1.vcf.gz 
<font color="#4E9A06"><b>acarrasco@kronos</b></font>:<font color="#3465A4"><b>/mnt/rreal/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/results/GWAS/Nalls23andMe_2019/BST1/LD</b></font>$ cat BST1.1KGphase1.vcf
</pre>

Same output when I tried to use the phase 3 from 1000G Panel

**Conclussion**

I believe there is an issue accessing the 1000Genome Ref Panel. When I changed the reference panel to UKB, the finemap_loci() function worked

**Comment by bschilder** [comment]
Hey @AMCalejandro, sorry for taking so long to get back to you. 

I think this is resolved now (just tested it). Not 100% why it occurred, but might be that 1KG API was down for a bit. This has happened intermittently in the past, perhaps when they're doing construction on the server.

The other possibility is that querying with tabix from the CLI from your IP address was temporarily blocked (too many calls per second). I'm not aware of this behaviour on 1KG's server specifically, but i know this can happen on servers in general.

In the echoverse branch i've moved away from the CLI wrapper and instead opted to use `seqminer` and`RSAMtools` via `echotabix`. This method is a bit slower but tends to be more robust, I've noticed, perhaps due to some extra checks and self-imposed timeouts to avoid exactly these kinds of issues. I've also built in some additional checks myself to ensure the vcf file isn't somehow there but empty (and if so, removes them with a warning).

In the meantime, let me know if this is still happened when using the master branch version.
