### ISSUE TITLE
Liftover `dat` before querying LD panel

### ISSUE THREAD

**Issue by bschilder** [RajLabMSSM/echoLD#5]

**Comment by bschilder** [comment]
@omerwe could you remind me which genome build the pre-computed UKB LD panel is in? I'm sure I asked this a long time ago but I can't seem to recall now.

https://data.broadinstitute.org/alkesgroup/UKBB_LD

**Comment by omerwe** [comment]
@bschilder I'm afraid it's hg19... (this is the ref panel with which UKB was originally imputed, so there's nothing much I can do about it 🤷 )

**Comment by bschilder** [comment]
Thanks for the quick reply @omerwe! No problem at all, my strategy is actually to lift over the data I'm using to query the LD panel (rather than try and liftover the LD panel itself).

I've added this to the `echoLD` documentation so I don't forget.

Hope all is well with you 😄 

Best, 
Brian

**Comment by bschilder** [comment]
Updated documentation for `?echoLD::get_LD`.
![Screenshot 2022-08-28 at 12 02 01](https://user-images.githubusercontent.com/34280215/187070802-08bb15e2-ca7c-450d-a9d0-6441c1382466.png)
